#! /usr/bin/env bash

# ble.sh config file
# See https://github.com/akinomyoga/ble.sh/blob/master/blerc.template
# for documentation and defaults

bleopt editor=vim
bleopt prompt_eol_mark='⏎'
bleopt history_share=1
bleopt term_index_colors=auto

ble-import config/execmark
bleopt exec_elapsed_enabled='_ble_exec_time_tot>=25000'

# vim: filetype=bash
