#! /usr/bin/env python3

import os
import shutil

home = os.environ['HOME']
app_path = '.var/app/org.qutebrowser.qutebrowser/data/qutebrowser'

files = [ 'webengine', 'greasemonkey' ]

for file in files:
    path = os.path.join(home, app_path, file)
    if path:
        print("Removing %s" % path)
        try:
            shutil.rmtree(path)
        except OSError as e:
            print(e)

