#! /usr/bin/env sh

appimage="${1}"
basepath="$(cd "$(dirname "${0}")" && pwd)"
appimagepath="${basepath}/.AppImages/${appimage}.AppImage"
shift

if [ -z "${appimage}" ]; then
	echo "Error: no AppImage specified to run" 1>&2
	exit 1
fi

if ! [ -x "${appimagepath}" ]; then
	echo "Error: cannot find ${appimagepath} or not executable" 
	exit 1
fi

if command -v ldconfig 1>/dev/null 2>&1; then
	libs="$(ldconfig --print-cache | grep '^[[:space:]]\+libfuse2.so\(\.2\)\?')"
	if [ -n "${libs}" ]; then
		exec "${appimagepath}" ${@}
	fi
fi

exec "${appimagepath}" --appimage-extract-and-run "${@}"

