#! /usr/bin/env python3

# Script to cleanup qutebrowser leftovers
# to remove tracking/cookies and other browsing data
# NO settings are removed, only temporary files.
# Supports flatpak install and from package manager

import os
import shutil

home = os.environ['HOME']
app_path = ['.var/app/org.qutebrowser.qutebrowser/data/qutebrowser', '.local/share/qutebrowser']

files = [ 'webengine', 'greasemonkey' ]

for base in app_path:
	for file in files:
		path = os.path.join(home, base, file)
		if path and os.path.isdir(path):
			print("Removing %s" % path)
			try:
				shutil.rmtree(path)
			except OSError as e:
				print(e)

# vim: filetype=python
