#! /usr/bin/env sh

# This script opens a new graphical browser window
# trying different browsers until one could be openend
# The order is opinionated

if flatpak info org.qutebrowser.qutebrowser 1>/dev/null 2>&1; then
	flatpak run org.qutebrowser.qutebrowser
elif command -v qutebrowser 1>/dev/null 2>&1; then
	qutebrowser
elif flatpak info org.mozilla.firefox 1>/dev/null 2>&1; then
	flatpak run org.mozilla.firefox
elif command -v firefox 1>/dev/null 2>&1; then
	firefox
elif flatpak info org.chromium.Chromium 1>/dev/null 2>&1; then
	flatpak run org.chromium.Chromium
elif command -v chromium 1>/dev/null 2>&1; then
	chromium
else
	echo "Error: no browser found" 1>&2
	exit 1
fi

# vim: filetype=sh
