#! /usr/bin/env sh

# Script to cleanup qutebrowser leftovers
# to remove tracking/cookies and other browsing data
# NO settings are removed, only temporary files.
# Supports flatpak install and from package manager


cleanup()
{
	base="${1}"
	if [ -d "${base}/webengine" ]; then
		echo "Removing ${base}/webengine"
		rm --recursive --force "${base}/webengine"
	fi
	if [ -d "${base}/greasemonkey" ]; then
		echo "Removing ${base}/greasemonkey"
		rm --recursive --force "${base}/greasemonkey"
	fi
}

cleanup "$HOME/.var/app/org.qutebrowser.qutebrowser/data/qutebrowser"
cleanup "$HOME/.local/share/qutebrowser"

# vim: filetype=sh
