[colorschemes.selenized_dark]
bg_0  = "103c48"
bg_1  = "184956"
bg_2  = "2d5b69"
dim_0 = "72898f"
fg_0  = "adbcbc"
fg_1  = "cad8d9"

red     = "fa5750"
green   = "75b938"
yellow  = "dbb32d"
blue    = "4695f7"
magenta = "f275be"
cyan    = "41c7b9"
orange  = "ed8649"
violet  = "af88eb"

br_red     = "ff665c"
br_green   = "84c747"
br_yellow  = "ebc13d"
br_blue    = "58a3ff"
br_magenta = "ff84cd"
br_cyan    = "53d6c7"
br_orange  = "fd9456"
br_violet  = "bd96fa"

[colorschemes.selenized_black]
bg_0  = "181818"
bg_1  = "252525"
bg_2  = "3b3b3b"
dim_0 = "777777"
fg_0  = "b9b9b9"
fg_1  = "dedede"

red     = "ed4a46"
green   = "70b433"
yellow  = "dbb32d"
blue    = "368aeb"
magenta = "eb6eb7"
cyan    = "3fc5b7"
orange  = "e67f43"
violet  = "a580e2"

br_red     = "ff5e56"
br_green   = "83c746"
br_yellow  = "efc541"
br_blue    = "4f9cfe"
br_magenta = "ff81ca"
br_cyan    = "56d8c9"
br_orange  = "fa9153"
br_violet  = "b891f5"

[colorschemes.selenized_light]
bg_0  = "fbf3db"
bg_1  = "ece3cc"
bg_2  = "d5cdb6"
dim_0 = "909995"
fg_0  = "53676d"
fg_1  = "3a4d53"

red     = "d2212d"
green   = "489100"
yellow  = "ad8900"
blue    = "0072d4"
magenta = "ca4898"
cyan    = "009c8f"
orange  = "c25d1e"
violet  = "8762c6"

br_red     = "cc1729"
br_green   = "428b00"
br_yellow  = "a78300"
br_blue    = "006dce"
br_magenta = "c44392"
br_cyan    = "00978a"
br_orange  = "bc5819"
br_violet  = "825dc0"

[colorschemes.selenized_white]
bg_0  = "ffffff"
bg_1  = "ebebeb"
bg_2  = "cdcdcd"
dim_0 = "878787"
fg_0  = "474747"
fg_1  = "282828"

red     = "d6000c"
green   = "1d9700"
yellow  = "c49700"
blue    = "0064e4"
magenta = "dd0f9d"
cyan    = "00ad9c"
orange  = "d04a00"
violet  = "7f51d6"

br_red     = "bf0000"
br_green   = "008400"
br_yellow  = "af8500"
br_blue    = "0054cf"
br_magenta = "c7008b"
br_cyan    = "009a8a"
br_orange  = "ba3700"
br_violet  = "6b40c3"
